dlang/tools

- posix.mak
- win32.mak
Needs https://github.com/D-Programming-Language/dlang.org/pull/900
> Hand off d.tag generation to dlang.org makefiles

- posix.mak
Is there any reason it's been left out?
> add dustmite to install

- rdmd.d
- rdmd_test.d
https://issues.dlang.org/show_bug.cgi?id=14259
> fix Issue 14259 - rdmd: --build-only / -of / -od incompatible with --dry-run

- changed.d
generate bugzilla changelog list from git commits
- parse commit messages for all repos in revList using
the same regex as the github bugzilla integration
- query bugzilla for details on those bugs and make sure
they are still marked as resolved and fixed
> update component names

- README.md
https://issues.dlang.org/show_bug.cgi?id=14715
> fix Issue 14715 - Add README.md to the tools Repository

- rdmd.d
- rdmd_test.d
https://issues.dlang.org/show_bug.cgi?id=15031
> fix Issue 15031 - rdmd should force rebuild when --compiler changes

- man/man1/rdmd.1
- rdmd.d
- rdmd_test.d
https://issues.dlang.org/show_bug.cgi?id=15173
https://issues.dlang.org/show_bug.cgi?id=15174
https://issues.dlang.org/show_bug.cgi?id=15175
> rdmd fixes

- dget.d
- latest-tag
- rdmd.d
- update.sh
update links to our new namespace :)
> update links to dlang

- rdmd.d
(split off https://github.com/dlang/tools/pull/183)
> rdmd: Fix --eval (update import list)

- ddemangle.d
On some architectures, symbols have an extra underscore prepended (e.g. OS X), and e.g. C++ symbols look like: `__ZZN4llvm14MCObjectWriter10WriteZerosEjE5Zeros`.
DMD does not prepend the extra `_` for D symbols: `_D6object9Throwable8toStringMFZAya` and ddemangle works fine.
LDC does prepend the extra `_`: `__D6object9Throwable8toStringMFZAya` and ddemangle does not demangle the symbol.
c++filt has the option `--strip-underscore     Ignore first leading underscore (default)` for this issue.
Instead of adding such a commandline switch, this commit makes ddemangle recognize both `_D...` and `__D...` during the same execution run. I could not come up with a case where it would do harm (already if the symbol doesn't succesfully demangle, it is left unchanged)
> Also match D symbols that have an extra leading underscore.

- changed.d
For the lazy people out there.
> [trivial] make changed.d runnable

- changed.d
BUGSTITLE generates an OL for the LIs.
> remove wrong P around LIs

- changed.d
- posix.mak
I also fixed a warning which prevented the compilation of change.d. There was a dangling else, so I added braces to get rid of the warning.
> Updated makefile to use dmd/generated/os/release/model/dmd

- posix.mak
Follow-up to https://github.com/dlang/tools/pull/227#issuecomment-312739111
CC @CyberShadow @WalterBright
> Document osmodel.mak loading from ../dmd

- rdmd.d
- also see https://github.com/dlang/dmd/pull/7110
> fix slice to temporary static array

- DustMite/dustmite.d
- DustMite/splitter.d
See also https://github.com/dlang/tools/pull/258 and https://github.com/CyberShadow/DustMite/pull/52
> Update DustMite to 7403f0d053b96b2c21950df038923b5d335d557f

- .mailmap
I also sorted this file alphabetically, hence "Yao Gómez" got a different position.
> Improve .mailmap

- changed.d
Step (2) of https://github.com/dlang/dlang.org/pull/1838
> Unify changelogs and insert generic macros

- changed.d
- contributors.d
Instead of https://github.com/dlang/dlang.org/pull/1977
> Emit list of contributors during the changelog generation

- .mailmap
- @somzz (Lucia) is a student of Andrei and publicly known (DConf, DBlog, Forum ...) as a contributor
- Added the last name for miles
- Added another mail address for "Ulrich Küttler"
> Improve contributor .mailmap mapping

- .mailmap
See also: http://forum.dlang.org/post/nudyyurlraexoaqkghrx@forum.dlang.org
This also adds a command to consistently the file with GNU's `sort` (instead of vim's sort before).
If done correctly, 5 lines should disappear on the diff.
> More Mailmap improvements

- rdmd.d
> Revert "Use "-i" to prevent rdmd from having to invoke compiler twice."

- CODEOWNERS
Not that we have many active reviewers here, but it's still good to document things.
Anyone else around who would be interested to join the CODEOWNERS - it's just about getting pinged to modifications of files you care about.
> Add a CODEOWNERS file for tools

- setup.sh
- travis.sh
Alternative to https://github.com/dlang/tools/pull/308
(I know that ideally I would have split the first commit into more parts, but I didn't expect setup.sh to be such a mess)
> Cleanup setup.sh + bash compatible + full shellcheck + run on Travis

- changed.d
It could be refactored to save the first `dirEntries` result but that would require more changes and complication which imho isn't worth the hassle.
Requires https://github.com/dlang/phobos/pull/6287
> Add a sanitycheck to ensure that changelog files end with .dd

- posix.mak
See also: https://github.com/dlang/dmd/pull/8093
> posix.mak: use -f to fix nightlies

- appveyor.yml
- rdmd.d
- rdmd_test.d
Please see the individual commits and their commit messages for details.
CC @WebDrake @marler8997
> rdmd and testsuite Windows fixes

- rdmd_test.d
Allows running most of the rdmd test suite even on systems with old GNU Make, such as Travis CI.
> rdmd_test: Don't attempt to run Makefile test when Make is too old

- README.md
> Add DUB build explanation to the README

- .mailmap
Auto-sorted with:
```
(head -n3 .mailmap && tail -n+4 .mailmap | sort -f) > .mailmap.tmp && mv .mailmap.tmp .mailmap
```
> Add more duplicate contributors to the mailmap file

- changed.d
This exposed two new macros for consumption in the `pending.ddoc` templates.
Example:
```
Macros:
VER=2.080.0
NR_BUGZILLA_ISSUES=93
NR_MAJOR_CHANGES=12
```
I'm not sure what the best approach is though, because DDoc doesn't support conditionals.
This means that if I use `$(NR_BUGZILLA_STATS)` in the changelog ddoc template, it will look strange for the previous changelog entries.
- Well, of course, I could generate this information for the past changelog entries, but I'm not sure whether that's really worth it
- "Forking" the Ddoc template doesn't sound like a good idea (especially given that more improvements might be added over time)
- Parsing the DDoc in the DDoc pregenerator sounds like a broken approach too
So I went with the this solution that defines an optional DDoc Macro that …
> Allow to print simple changelog statistics

- DustMite/splitter.d
- appveyor.yml
- posix.mak
Also adds the -dip25 flag to the Makefile
> Make DustMite -dip25 compliant

- posix.mak
> Build everything with -preview=dip1000

- changed.d
See e.g. https://github.com/dlang/dmd/pull/10801
> Fix changelog generation for markdown code blocks

- changed.d
See https://github.com/dlang/dlang-bot/pull/240
> Improve regex for closed issues

- rdmd.d
- rdmd_test.d
Some issues are easier to fix that to transfer.
> Fix issue 13345 - Add argument support to rdmd --eval

- changed.d
- new regex expects fix to start line
> fix changelog generator

- changed.d
> merge stable

- dget.d
- rdmd.d
I suggest to deprecate typetuple. To do so, it needs to be removed here.
> Remove typetuple

- tests_extractor.d
Allows Phobos/... to define tests that should not be executed on the command line.
See dlang/phobos#8009
CC @CyberShadow
> test_extractor: Skip versions passed via command line

- changed.d
Counterpart of https://github.com/dlang/dlang-bot/pull/302.
https://forum.dlang.org/post/gebtpqatonfsgkcqptym@forum.dlang.org
> tools.changed: Allow the word "Bugzilla" to appear in issue references

- tests_extractor.d
Unblocking https://github.com/dlang/dmd/pull/16315 hopefully
> tests_extractor.d: Upgrade libdparse
