rdmd.d

This warning has been there for almost a year now, it was introduced by
issue #133. By now all projects should be properly updated. Also, there
is no way to disable the warning, which is triggered even for projects
that are already updated, which makes it extra annoying.

rdmd: Remove tango warning

---

ddemangle.d

Warning with 2.071.0:
`ddemangle.d(17): Deprecation: module std.c.stdlib is deprecated - Import core.stdc.stdlib or core.sys.posix.stdlib instead`

Fix import deprecation warning.

---

.travis.yml
README.md
rdmd.d
travis.sh

I used digger to automatically get the latest HEAD version.
@CyberShadow would you be so kind to enable Travis? Thanks!
https://travis-ci.org/dlang/tools

Enable Travis with rdmd testsuite

---

rdmd.d

This immediately jumped into by eye during the discussion and review at #191. We only iterate once through the collection.

Remove unneccsary array allocation

---

rdmd.d

These are two simple gotchas that I found during #195 and are independent to it or any refactoring.
Btw interestingly the compilation increases about 0.1s, but for the optimized build it decreases for nearly 0.2s
Compilation
---------------------
command | compilation time
-------------------|--------------------
|`dmd rdmd-master.d` | 1.21s
|`dmd rdmd.d` | 1.31s
|`dmd -O rdmd-master.d` | 1.96s
|`dmd -O rdmd.d` | 1.77s
```
echo rdmd_master.d rdmd.d "-O rdmd" | tr ' ' '\n' | parallel -j1 "echo {}; python -m timeit -n 5 -r 3 -s 'import os' 'os.system(\"dmd {}\")'"
```
Run time
---------------
With the used at #191 
command | compilation time
-------------------|--------------------
|`rdmd-master` | 607ms
|`rdmd-ct` | 605ms
|`rdmd-master-opt` | 598ms
|`rdmd-ct-opt` | 557ms
For a simple file …

use ctRegex + avoid array allocation

---

rdmd.d

As suggested by Andrei in [a comment](https://github.com/dlang/tools/pull/191#issuecomment-242746480) on #191. Consequently, this is an alternative to #191.
Used bash's builtin `time` with `TIMEFORMAT=%R` to get simple output.
All times are the best of 3 runs.
`rdmd_master` is the current master (1260719a9ce64b012dac5c6287e179353afaaefa).
`rdmd_single_out_root` is the one from this PR.
foo.d is <http://sprunge.us/ZZhR>, taken from #191.
```
$ time ./rdmd_master --force foo.d > /dev/null
1.142
$ time ./rdmd_single_out_root --force foo.d > /dev/null
0.747
```
Good improvement here.
bar.d is `import foo;`.
```
$ time ./rdmd_master --force bar.d > /dev/null
0.935
$ time ./rdmd_single_out_root --force bar.d > /dev/null
0.937
```
As expected, no change here.
baz.d is foo.d plus `import qux;`. …

rdmd: compile the root module in the same step as getting the dependencies

---

README.md

Adds more nice badges to the tools repo.
The tag badge will automatically show the latest git tag and the issue stats is intended as positive motivation for contributors.

Add tag & stats badges to the README

---

ddemangle.d

It was not possible to use _ddemangle_ as a service because it didn't flushed each new line. Now an IDE can execute the tool only once and use it when needed. Previously it was impossible and an IDE had to launch the process each time it had something to demangle, which was not optimal.

ddemangle, flush output for each new demangled line

---

dget.d

https://issues.dlang.org/show_bug.cgi?id=16593

Fix Issue 16593 - Building "tools" produces deprecation warnings

---

README.md
phobos_tests_extractor.d

Adds a simple extraction utility that dumps all public unittests from Phobos in separate files, s.t. we can run them with `rdmd` and verify that all snippets on dlang.org are runnable (e.g. don't miss imports).

Add Phobos public tests extractor script

---

README.md
styles/.gitignore
styles/dub.sdl
styles/dub.selections.json
styles/has_public_example.d
styles/tests_extractor.d
styles/utils.d

From the proof-of-concept [PR](https://github.com/dlang/phobos/pull/4973), here's the tool to check for public functions without unittests. As it also requires `libdparse`, I created a `styles` folder in which these tools can be put & added an according `dub` configuration.
In went for the `tools` repo, because many people have access to it & I thought it's better than privately hosting such a style checking repo.
As detecting the ddoc header turns out to be more complicated, I put the logic into a common `utils` module and changed the existing `tests_extractor` accordingly.
I also included #206 and #208.

Add has_public_example and tests_extractor

---

changed.d

As discussed in [the phobos PR](https://github.com/dlang/phobos/pull/4228) this adds the changelog builder to the tools repo.
I also modified the `changed` tool to accept an additional output flag.

add changelog from directory builder

---

changed.d

- a few changes for the changelog tool

fixup for #186

---

osmodel.mak
posix.mak

In order to compile the "tools" on a lot of operating systems, I'd like to suggest to use osmodel.mak.
https://issues.dlang.org/show_bug.cgi?id=15282

Issue 15282 - Import osmodel.mak from dmd to detect OS and MODEL

---

rdmd.d
rdmd_test.d

Was: #218. Now targetting stable.

fix issue 17198 - rdmd does not recompile when --extra-file is added

---

changed.d

When there are no issues in the git log, the bugzilla query is empty and thus all issues get loaded. This is  fix that solves the problem by simply returning earlier and thus not sending the Bugzilla query.
Also there's also the category "VisualD" on Bugzilla into which on might run as well (even though it's currently not on list of parsed repos).
Moreover, as dlang.org changelog scheme is without "v", there's another simple fix that prints the previous version with the "v" prefix.

Handle empty issue list more gently + avoid fetching the git remote directly

---

styles/tests_extractor.d

The test extractor visited only first-level declarations. With this fix, it looks at nested declarations as well.

Test extractor: visit the entire AST tree

---

changed.d

It seems like some macros like `CONSOLE` don't like whitespace indentation.
Before
After:
See also: https://github.com/dlang/phobos/pull/5001

Changed.d: Remove leading whitespace in changelog output

---

changed.d

I didn't realize that when we provide different Makefile targets (with `BUILD_NIGHTLY`) we can override even more logic :)

Use alternative header for nightly builds

---

osmodel.mak

- The `osmodel.mak` files weren't in sync
- Since a couple of weeks the `tools` and `dlang.org` repo use the same file
Btw this manual sync seems very error-prone and labour-intensive.
Why can't we do an `include $(DMD_DIR)/src/osmodel.mak`?

osmodel.mak: Mention tools + dlang.org repos in the update reminder

---

checkwhitespace.d

Since the file dmd/src/checkwhitespace.d has nothing to do with the compiler implementation, it should be moved to the tools repo. After this PR is merged and all scripts that use checkwhitespace.d from its current location are modified, the dmd/src/checkwhitespace.d will be deleted

Added dmd/src/checkwhitespace.d to tools repo

---

rdmd.d

Seems like manually maintaining the docs is a bad idea ;-)
Any reason why e.g. [defaultGetoptPrinter](https://dlang.org/phobos/std_getopt.html#.defaultGetoptPrinter) wasn't used?

Issue 17262 - Better docs for rdmd

---

changed.d

Prevents mistakes such as https://github.com/dlang/dmd/pull/6912.

changed: Validate changelog entry files

---

changed.d

This stabilizes the changelog order, preventing [non-deterministic website builds](http://dtest.dlang.io/results/8b8dd5c9930e01efce763ae18d9053a5bfb63ce4/dc5e167b034348d80b8fdadbb149a2426930c8e4/), and also allows ordering the entries manually by naming the files according to the desired lexicographical order.
CC @wilzbach

Sort changelog entry files by file name

---

setup.sh

This little tool worked great when setting up a completely new computer. It's quite underrated!
This diff gives it a more intuitive name and makes it work with no previously installed dmd.

Rename update.sh to setup.sh and make it work with auto-boostraping

---

rdmd.d

Remove deprecated stdc import

---

.travis.yml
dman.d
posix.mak
travis.sh

Follow-up to https://github.com/dlang/tools/pull/238
> Maybe build tools with `-de`?
Good idea - especially with daily crons form Travis we should get notified when stuff breaks.
Supersedes https://github.com/dlang/tools/pull/233

Improve testing

---

rdmd.d

Looks like nobody is using --eval or --loop...

rdmd: Update imports for --eval and --loop

---

posix.mak
rdmd_test.d
travis.sh

Follow-up to https://github.com/dlang/tools/pull/239#issuecomment-312869044
This should make (1) it a lot easier to run the test suite properly (after all it's now part of the `test` Makefile target) and (2) should be a good step into debugging why Travis build succeed.
Currently, however, it fails:
```
pmake test_rdmd
../dmd/generated/linux/release/64/dmd -I../druntime/import -I../phobos -L-L../phobos/generated/linux/release/64 -m64 -w -de -ofgenerated/linux/64/rdmd_test rdmd_test.d
../phobos/std/parallelism.d(3523): Warning: statement is not reachable
../phobos/std/parallelism.d(3523): Warning: statement is not reachable
make: *** [posix.mak:72: generated/linux/64/rdmd_test] Error 1
```
I have looked into fixing `rdmd_test` two weeks ago and the fix for this is still in the Phobos …

Run rdmd testsuite properly

---

travis.sh

https://github.com/dlang/tools/pull/244/files#r125533867
> I'd suggest pinning Digger to a specific version (as with DScanner) to avoid the breaking changes in Digger's master from affecting tools.

Pin digger to a specific version

---

tests_extractor.d

In the spirit of removing deprecation warnings, s.t. they don't bite us later.
```
../../../.dub/packages/libdparse-0.7.0/libdparse/src/dparse/ast.d(1346,10): Deprecation: cannot implicitly override base class method object.Object.opEquals with dparse.ast.Declaration.opEquals; add override attribute
tests_extractor ~master: building configuration "application"...
../../../.dub/packages/libdparse-0.7.0/libdparse/src/dparse/ast.d(1346,10): Deprecation: cannot implicitly override base class method object.Object.opEquals with dparse.ast.Declaration.opEquals; add override attribute
```

Upgrade libdparse (remove deprecation warnings)

---

changelog/b11997.dd
rdmd.d
rdmd_test.d

`rdmd` should work out of the box now, without having to add it to your `PATH`, tested with dmd and ldc, which just started shipping with `rdmd`.  Would be nice to get this in before the final 2.075 release of dmd, pinging @MartinNowak.
Only drawback I can see is that if someone takes rdmd and puts it in some arbitrary directory with a file that's happened to be named `dmd` or `ldmd2`, `rdmd` will now try to run it.  Seems far-fetched, but the real solution is to just integrate `rdmd` with dmd and ldc, so this external script doesn't always have to go find them.

Fix Issue 11997 - rdmd should search it's binary path for the compiler

---

dman.d
posix.mak
win32.mak

Needs https://github.com/dlang/dlang.org/pull/1860.
Fixes issue 17731.

dman: Use d-tags.json instead of d.tag

---

posix.mak

As long as https://github.com/dlang/dmd/pull/7002 isn't merged, the development DMD compiler won't use `-fPIC` by default (the released compiler does use `-fPIC` by default).

Use DFLAGS for DUB builds + -fPIC by default

---

posix.mak
win32.mak

- fixes remaking dlang.org when tool's Makefile is used by build scripts
- allows to build dman for prereleases, latest, or releases
Win rule untested!

leave it to user to build d-tags.json

---

.mailmap
contributors.d
posix.mak

I don't know yet how we are going to integrate this on dlang.org, but this script should be more than flexible enough to accompany many possible scenarios.
Ideas:
- Add to the bottom of each changelog
- Separate page for each changelog (linked from changelog) (that's how [the Rails people](http://contributors.rubyonrails.org/) or [the Rust people handle this](https://thanks.rust-lang.org/rust/1.19.0))
- All contributors page (the tool is more than fast enough, s.t. we could run this on every deploy)

Add script to query for contributors between two releases

---

tests_extractor.d

This will get rid of these annoying errors:
```
std/concurrency.d(759:37)[error]: declaration expected instead of '{'
std/concurrency.d(761:23)[error]: Declaration expected
std/concurrency.d(762:5)[error]: Declaration expected
std/concurrency.d(762:6)[error]: Declaration expected
std/concurrency.d(763:24)[error]: declaration expected instead of '{'
std/concurrency.d(763:35)[error]: Declaration expected
std/concurrency.d(763:36)[error]: Declaration expected
std/concurrency.d(764:25)[error]: declaration expected instead of '{'
std/concurrency.d(764:36)[error]: Declaration expected
std/concurrency.d(764:37)[error]: Declaration expected
```
.
~~~CircleCi checks out a fixed version of tools. This needs to be bumped too, afterwards.~~~

Bump libdparse

---

appveyor.yml

> Win rule untested!
-> let's add a CI to introduce light into the dark.
See also: https://github.com/dlang/installer/pull/275

Add AppVeyor config file to test win32.mak

---

.mailmap

His various email addresses are gleaned from git log. Not sure if this is all of them, but should cover the ones used in Phobos.

Update .mailmap entry for Dicebot / Михаил Страшун.

---

rdmd.d

Should result in a big performance improvement to rdmd (about 30% decrease in run time).  Depends on this commit from dmd (https://github.com/dlang/dmd/pull/7099).

Use "-i" to prevent rdmd from having to invoke compiler twice.

---

contributors.d

It will try to check for other `dlang` repositories when `--all` is used. If they aren't found it will softly fail and print a warning to stderr.

Improve contributors script

---

rdmd.d

Note, this doesn't affect linux, only windows.  The problem is that the inner/outer loops for searching for a program in the `which` function is in the wrong order.  You should go through each PATH, and in each one search for a program matching every extension in PATHEXT.

Modify `which` function to match Windows search behavior.

---

rdmd_test.d

This patchset reworks the test-suite functions inside `rdmd_test` to allow them to be run with an arbitrary choice of `rdmd` executable, D compiler invoked by `rdmd`, and target model (32- or 64 bits).  These new features are then used to implement a new `--test-compilers` flag, which allows the user to specify a comma-separated list of different compiler names to run the test suite with.  If no test compilers are specified, the test suite will be run using the same compiler as used to build `rdmd` (the "build compiler").
This should result in identical behaviour of `rdmd_test` in cases where `--test-compilers` are not specified, but will allow CI to be updated in future to ensure that `rdmd` is tested with all the compilers that `rdmd` should support.  This should help to avoid repeats …

Rework rdmd_test to support running test suite with multiple different compilers

---

.travis.yml
travis.sh

Digger was added to be able to test `tools` with the latest DMD.
So Digger builds the latest `dmd`, `druntime` and `phobos` and we have enabled a daily cron here that checks every day that things are still working.
However, now that we have the Project Tester we can simply add `dlang/tools` to it and thus be on the safe side as the testsuite is now run on every PR.
The respective dlang/ci PR is: https://github.com/dlang/ci/pull/130

Remove digger setup and use the compiler from Travis

---

posix.mak

- e.g. to test dlang/tools without erroring on deprecations (ci.dlang.org)
- use `override DFLAGS +=` for non-configurable target specific flags

allow to configure DFLAGS and WARNINGS

---

.travis.yml

For some reason 32-bit builds are only tested for stable `dmd`.  This seems an oversight: we don't want to find out that the D tools break 32-bit `dmd` only after a stable release has come out!
This patch therefore adds an extra Travis build with `DMD=dmd-nightly` and `MODEL=32`.

Add 32-bit dmd-nightly builds to Travis CI

---

posix.mak
travis.sh

These patches introduce a simple proof-of-concept for using `rdmd_test`'s new `--test-compilers` flag in CI.  The `posix.mak` makefile has been extended with a new `RDMD_TEST_COMPILERS` variable, which can be used to set the choice of compilers to be tested with `rdmd_test`.  This is then used to update Travis CI settings to test with both `dmd` and `ldmd2` (with the latter being installed as a distro package).  `gdmd` is not included for the time being since installing it would have been trickier (there is a `gdc` distro package available but it does not include the `gdmd` perl script).
The last patch is added just for testing purposes and should probably be dropped before this PR is accepted: it makes the `test_rdmd` make target run `rdmd_test` verbosely so that we can clearly see the …

Use multiple different test compilers when invoking rdmd_test from Travis CI

---

travis.sh

This is probably unnecessary for the use-case but can never hurt, so let's follow shellcheck's nice and helpful hints ;-)
@wilzbach thanks for the introduction to the nice tool, it's one I didn't know before.

Quote variables in travis.sh to prevent word splitting

---

changed.d

First step of integrating dub's changelog with the DMD release annoucement.
This will at least allow for manual changelog entries to be part of the release.
It can't query issues at the moment because
- a different tagging version system is used
- DUB doesn't have a Bugzilla issue tracker (and we haven't integrated GH issues so far)
See also: https://github.com/dlang/dlang.org/pull/2163

Issue 18351 - integrate dub changelog with changed.d tool

---

rdmd.d

File types are split into more than just directories and files.  In this case, `fullExe` must be a regular file, so checking `isFile` removes any question about whether or not it is actually a file.  The current implementation uses `!isDir` which could still be true even if `fullExe` is not a regular file, which is not the logic we want here.

Change !isDir to isFile

---

changed.d

This allows the following DDoc style in the changelog entries:
```
---
int result;
---
```
This is needed to fix the nightly changelog: http://dlang.org/changelog/pending.html
As the branch-off is about to happen soon a fast merge would be appreciated. Thanks!
Before:
After:
CC @CyberShadow

Improve codeblock detection

---

checkwhitespace.d

To allow running checkwhitespace on files not recognized by the program, e.g:
```
checkwhitespace --allow-tabs Makefile
```
As for the option itself: `--allow-xxx`, `--disable-xxx`, `--nocheck-xxx`, I don't really mind what it's called.

checkwhitespace.d: Allow individual errors to be turned off.

---

rdmd_test.d
travis.sh

This patch updates travis.sh to install GDC and to include the DMD-alike `gdmd` compiler frontend among the `RDMD_TEST_COMPILERS`.
Since GDC does not yet implement `pragma(lib)`, the `rdmd_test` case for this has been disabled for the case where `gdmd` is the test compiler.

Add gdc/gdmd to compilers tested by Travis with rdmd_test

---

rdmd.d

This reverts the functional changes of #303, but keeps the refactoring.
Motivation:
In #317 we might figure out a way to be smarter about lines without a semi-colon,
so publishing this now would limit our abilities to change the behavior later.
----
The master-stable branch-off is supposed to happen in two days, so a quick pull would be appreicated.
Thanks!
CC @CyberShadow @marler8997 @WebDrake

Partially revert #303 until #317 is resolved

---

changed.d

Follow-up to https://github.com/dlang/dlang.org/pull/2184
Pretty stupidly simple for now:
Requires the Ddoc macros first to prevent DAutoTest from failing - see https://github.com/dlang/dlang.org/pull/2203

Emit new CHANGELOG_SOURCE_FILE DDoc macro

---

setup.sh
travis.sh

Apparentely the `--tag` option for the `setup.sh` never worked...

Fix Travis: fix checking out tags with setup.sh

---

dget.d
posix.mak

- Add support for overwritting BUILD variable using "make -f posix.mak BUILD=debug"
- Use $(BUILD) instead of 'release'
- Add -L/usr/local/lib/ when building on dragonflybsd, required because curl is installed in /usr/local/lib. Might be required for other OS' as well.

[Trivial] Update tools:posix.mak

---

appveyor.yml
posix.mak
rdmd_test.d
win32.mak

One key problem of the old `rdmd_test` was that it built its own rdmd instance to test.  This meant that technically, it was never actually run against the rdmd executable generated in the regular tools build.
This rewrite fixes this by repurposing the `--rdmd` flag of `rdmd_test` to require not a path to `rdmd.d` but a path to the rdmd executable for which the test suite should be run.  The provided executable is not used directly, but is copied into a temporary directory: this is necessary in order to run the fallback test, which involves copying a dummy compiler into the same directory as the tested rdmd executable.
The `--compiler` flag has been removed (since `rdmd_test` no longer uses it to build an rdmd executable), but a new `--fallback-compiler` flag is now required in order to …

rdmd_test: rewrite to use externally-specifed rdmd executable 

---

changed.d

Hard-coding the explicit version is no longer required
See also: https://github.com/dlang/dlang.org/pull/2242
We should probably just emit a few macros, s.t. it's easier to change the structure in the future, but that's a battle for another day.

Use CHANGELOG_NAV_INJECT for the changelog generator

---

posix.mak
win32.mak

These patches correct some oversights in the `clean` targets declared by the makefiles.  These should ensure that all generated files are removed, not just the application binaries.
Note that this would automatically be dealt with if `clean` just removed the `$(ROOT_OF_THEM_ALL)` directory.  This option has been avoided so as to avoid changing the existing `clean` behaviour, since presumably there is some perceived risk associated with removing directories recursively.  However, it may be worth returning to this decision in future as (if it could be done safely) it would greatly simplify declaration and maintenance of the `clean` target.
**Warning:** as a non-Windows dev I have not tested the patch to `win32.mak`, so someone may want to try this out in anger before accepting the PR ;-)

posix.mak, win32.mak: Ensure `clean` target removes all generated files and directories

---

posix.mak
rdmd_test.d
win32.mak

Non-option arguments are more conventional than "required options".

Since --rdmd is required, made it a "non-option" argument instead of an "option that is [REQUIRED]"

---

changelog/rdmdMakefiles.dd
rdmd.d
rdmd_test.d
travis.sh

This a patch to make rdmd work for makefiles using a -e flag.
```
.ONESHELL:
SHELL = /usr/bin/rdmd
.SHELLFLAGS = -e 
hello.txt:
import std.file;
write("$@","hello world\n");
```
note --eval= won't work in SHELLFLAGS because make passes SHELLFLAGS and the code in seperate arguments.
```
Invoked with: ["/home/superstar64/Desktop/tools/rdmd", "-e", "import std.file;\nwrite(\"hello.txt\",\"hello world\\n\");"]
```

rdmd: support --eval <arg> to make it Makefile friendly

---

.gitignore
dub.sdl
test/test_dub.sh
tests_extractor.d
travis.sh

Allows using the tools from anywhere with e.g.
```
dub run dtools:tests_extractor
dub run dtools:detab
```

Allow using the tools repo via DUB

---

test/tests_extractor/ascii.d.ext
test/tests_extractor/iteration.d.ext
tests_extractor.d

Previously, the line numbers of an error wasn't the same as the original file.
This `#line` tricks saves the trouble of looking up the offending line via the in-line comment.

Display the correct line number when executing the extracted public tests

---

man/man1/rdmd.1

The first place I looked for information/help was the man page but information on the --shebang option is missing (although it does appear in the --help text).
As a result, it took me far too long to find this information - I eventually found the information on a forum post somewhere after a few fruitless searches - adding it to the man page will hopefully save someone else from doing the same if they look there first.

Add information about the --shebang switch to the rdmd man page.

---

README.md
posix.mak
updatecopyright.d

I've been a bit under the weather today, so I hacked together something that updates all copyright notices in all dmd sources in a consistent manner, with an `--update-year`/`-y` to automate updating the copyright year of sources also.
I would have thought that something like this exists, but couldn't see anything at a glance.

Add update_copyright script.

---

test/tests_extractor/ascii.d.ext
test/tests_extractor/attributes.d.ext
test/tests_extractor/iteration.d.ext
tests_extractor.d

While the underlying issue is https://issues.dlang.org/show_bug.cgi?id=19873, fixing this allows the Phobos PR to move on for now.
tl;dr: the publictest extractor now extracts the respective system attributes too.
Required for https://github.com/dlang/phobos/pull/6931

Parse unittest attributes and write them to the publictest tester

---

test/tests_extractor/ascii.d.ext
test/tests_extractor/iteration.d.ext
tests_extractor.d

They are handled differently in libdparse, but while I was at it, it's probably a good idea to support them too to avoid any potential confusion.
See also: https://github.com/dlang/tools/pull/369

tests_extractor: extract pure + nothrow too

---

setup.sh

ShellCheck version is unpinned so CI update caused master to break. Fix the warnings reported by the current CI version.

setup.sh: Fix ShellCheck warnings

---

tolf.d

Currently `tolf` will remove terminating newlines from files.  This PR modifies it to keep the existing trailing newline if there is one, or add it if it doesn't have one.  This causes `tolf` to modify files according to the posix standard (see https://forum.dlang.org/post/mailman.1025.1573349185.8294.digitalmars-d@puremagic.com for reference).

Have tolf keep and/or add terminating newline

---

.mailmap

Alternative to #388, because in 388 my name and my email address are wrong; see my comment there.

Add email duplicate for Berni

---

setup.sh

```
As explained in issue 20727, AUTO_BOOTSTRAP is not required for 'clean',
but still triggers the error.
```
Tested locally, works for me.

Work around issue 20727 by passing BOOTSTRAP when doing clean

---

.github/ISSUE_TEMPLATE/feature_request.md

It was intended to be a reference to the DIPs but was moved to the body.

Issue template: Remove half-finished sentence for feature request

---

travis.sh

```
The installation of make was added in PR 336 as at that time Travis
was using Ubuntu 14.04 which had make 3.81, whereas 3.82 is required
for the test.
Nowadays Travis uses either 16.04 or 18.04, and 16.04 comes with make 4.1.
```
Just put the `make --version` in there to double check my sanity.
Version of make can be checked here: https://packages.ubuntu.com/search?keywords=make

Use system make for tests

---

tests_extractor.d

`hasDdocHeader` was only called if `decl.unittest_` wasn't null and
hence only executed the first if-branch.
The remainder of that method is obsolete because dparse sets `comment`
even for empty ddoc comments (see dlang-community/libdparse#401).
Relying on dparse also removes some false positives/negatives, e.g.
```
///
// Some comment
unittest {} // Ignored
////////////////////////////////////////////////////////////////////////////////
// Unit Tests
////////////////////////////////////////////////////////////////////////////////
unittest {} // Extracted
```
~~Note: This can be merged once dparse tags a new release containing the aforementioned PR.~~

Remove unused code from test_extractor.d

---

changed.d

Make it clear that the list of "regressions" is a list of regressions fixed, and not an "errata" of regressions introduced in this release.

changed: Clarify terminology

---

appveyor.yml
win32.mak
win64.mak

This is added so that the windows installer can use it to build the tools for the 64-bit version also. The file is mostly copy-paste from win32.mak.

Add win64.mak

---

rdmd.d

Extends the `defaultCompiler` selection s.t. custom defaults can be selected at compile time via `-version=DefaultCompiler_XXX` (where `XXX` is either `DMD`, `LDC` or `GDC`).
This allows the `rdmd` bundled with DMD to be built with LDC while still defaulting to DMD.
CC @Geod24  @rikkimax

rdmd: Allow selection of default compiler independent from the host one

---

rdmd.d

rdmd: Don't import std.xml for --eval and --loop

---

changed.d
contributors.d
posix.mak
setup.sh

It is now part of the dmd project.
In this scheme, all runtime changes will be bundled in with compiler ones, detected only by the changelog entry having an appropriate prefix.
Needed to generate the website changelogs for release.

Remove references to the archived druntime repository

---

dget.d

Those become required when using the latest compiler with DIP1000.

dget: Use explicit storage classes in delegate

---

appveyor.yml

This is now possible now the site now has a new front for its bucket.

Update downloads.dlang.org links to use https

---

changelog/rdmd_shared.dd
rdmd.d

- Fixes https://github.com/dlang/tools/issues/454

rdmd: Support -shared in the same way as -lib
